[resolvers.cloudflare-dot]
address = "1.1.1.1:53"
protocol = "udp"

[groups.node10]
type                = "blocklist-panel"
panel-refresh       = 1
resolvers           = ["cloudflare-dot"] # Anything that passes the filter is sent on to this resolver
allowlist-format    = "hostsx"            # "domain(x)", "hosts(x)" or "regexp", defaults to "regexp"
blocklist-format    = "domainx"            # "domain(x)", "hosts(x)" or "regexp", defaults to "regexp"
ipallowlist-format    = "cidr"            # "location", "cidr"(default)
api = { ApiHost="https://127.0.0.1", NodeID=10, Key="SSPANEL"}

[groups.cloudflare-blocklist]
type                = "panel-rotate"
# cert = { CertMode = "dns", CertDomain = "node1.test.com", "Refresh" = 600, CertFile="/etc/XrayR/cert/node1.test.com.cert", KeyFile="/etc/XrayR/cert/node1.test.com.key", Provider="alidns", Email="test@me.com", DNSEnv={ ALICLOUD_ACCESS_KEY="aaa", ALICLOUD_SECRET_KEY="bbb"}, RejectUnknownSni=false}
resolvers           = ["cloudflare-dot"] # Anything that passes the filter is sent on to this resolver

# [groups.smartdns-nonallowed]
# type             = "blocklist-v2"
# resolvers        = ["google-dot"] 
# blocklist-format = "hostsx"
# blocklist = [
#   'check2.beshcan.ir 127.0.0.1',
# ]

[listeners.local-udp]
address = ":53"
protocol = "udp"
resolver = "cloudflare-blocklist"

[listeners.local-tcp]
address = ":53"
protocol = "tcp"
resolver = "cloudflare-blocklist"

#[listeners.local-doq]
#address = ":8853"
#protocol = "doq"
#resolver = "smartdns-allowclient"
#cert = { CertMode = "dns", CertDomain = "node1.test.com", CertFile="/etc/XrayR/cert/node1.test.com.cert", KeyFile="/etc/XrayR/cert/node1.test.com.key", Provider="alidns", Email="test@me.com", DNSEnv={ ALICLOUD_ACCESS_KEY="aaa", ALICLOUD_SECRET_KEY="bbb"}, RejectUnknownSni=false}