name: publish
on:
  workflow_dispatch:
  push:
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB }}

      - name: Build and Push Docker Image
        run: |
          docker build --target routedns . --tag kontorol/routedns:latest
          docker push kontorol/routedns:latest
          docker build --target routednsdebug . --tag kontorol/routedns:debug
          docker push kontorol/routedns:debug
          docker build --target routednsxtls . --tag kontorol/routedns:xtls-latest
          docker push kontorol/routedns:xtls-latest